spring:
  application:
    name: hello-spring-cloud-consumer-feign
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka